[green_agent]
agentbeats_id = "019bbf50-8190-7972-b436-487fd7808aaf"
env = { PURPLE_AGENT_GEMINI_API_KEY = "${PURPLE_AGENT_GEMINI_API_KEY}", LOG_LEVEL = "INFO", GEMINI_API_KEY = "${GEMINI_API_KEY}"  }

[[participants]]
agentbeats_id = ""
name = "participant"
env = { PURPLE_AGENT_GEMINI_API_KEY = "${PURPLE_AGENT_GEMINI_API_KEY}", LOG_LEVEL = "INFO", GEMINI_API_KEY = "${GEMINI_API_KEY}"  }

[config]
role = "werewolf"
