[green_agent]
agentbeats_id = "019bbb08-f3ad-7fa0-b150-9d62ea4c5a1b"
image = "ghcr.io/agent-beats-uta/werewolf-arena-game-orchestrator:latest"
env = { API_KEY = "${GITHUB_SECRET_NAME}", LOG_LEVEL = "INFO", GEMINI_API_KEY = "${GEMINI_API_KEY}"  }

[[participants]]
agentbeats_id = ""
name = "participant"
env = {}

[config]
role = "werewolf"
