[green_agent]
agentbeats_id = "019bbf50-8190-7972-b436-487fd7808aaf"
image = "ghcr.io/agent-beats-uta/werewolf-arena-game-orchestrator:latest"
env = { API_KEY = "${GITHUB_SECRET_NAME}", LOG_LEVEL = "INFO", GEMINI_API_KEY = "${GEMINI_API_KEY}"  }

[[participants]]
agentbeats_id = "019bbf66-81af-7142-b3af-8987a98ee665"
name = "participant"
env = { API_KEY = "${GITHUB_SECRET_NAME}", LOG_LEVEL = "INFO", GEMINI_API_KEY = "${GEMINI_API_KEY}"  }

[config]
role = "werewolf"
